### PR TITLE
MTM-51147 Enterprise tenant DNS mapping: wrong info in Online documen…

### PR DESCRIPTION
**Pull request by karolkaczmarski-sag**
…tation

### CODE REVIEW

**Review by jkot-softwareag — APPROVED** [review]

**Review by BeateRixen — APPROVED** [review]

**Comment by BeateRixen** [comment]
@karolkaczmarski-sag I suppose that this should also be grafted to older versions?

**Comment by karolkaczmarski-sag** [comment]
> @karolkaczmarski-sag I suppose that this should also be grafted to older versions?

@BeateRixen yes, should I create grafts?

**Comment by BeateRixen** [comment]
> > @karolkaczmarski-sag I suppose that this should also be grafted to older versions?
> 
> @BeateRixen yes, should I create grafts?

No I can do that, to which versions does this change apply?

**Comment by BeateRixen** [comment]
> 

@karolkaczmarski-sag Grafted to all versions back to 10.11.

**Pull request merged**
