### PR TITLE
MTM-49618 replace screenshots with new design for support user sections

### PR DESCRIPTION
**Pull request by atishch1**
Support User related screenshot replaces with latest

### CODE REVIEW

**Comment by rssag** [comment]
the screenshots are all bigger. why is that?

**Comment by atishch1** [comment]
@rssag  I just compared with current screenshot and this PRs. Both looks the same size and takes the full width of the screen. It looks bigger in the PR as it's of higher resolution, which is fine I guess. 

I feel we should have some width based setting so that it doesn't look odd when it's a very big screen but that can be taken care later as improvement to current documentation

**Review by BeateRixen — APPROVED** [review]

**Review by ashutoshstudy — APPROVED** [review]

**Review by ashutoshstudy — APPROVED** [review]

**Review by asda001 — APPROVED** [review]

**Comment by BeateRixen** [comment]
@atishch1 Shall I merge this PR?

**Comment by BeateRixen** [comment]
> @atishch1 Shall I merge this PR?

Just saw that there are conflicts, please resolve first.

**Pull request merged**
