### PR TITLE
[DM-2029] update-screens-for-CRA

### PR DESCRIPTION
**Pull request by dmajsag**

### CODE REVIEW

**Comment by BeateRixen** [comment]
@dmajsag Please be aware that the browser size when taking screenshots should be set to 1440 px width. The images in this PR are a bit smaller, but it is ok for now. Just for future work :-).
I recommend to delete the following images as they are of not much value and the process is obvious from the text:
cra-administration-settings
cra-device-list
cra-endpoint-add
cra-endpoint-connect
We aim at reducing the overall number of screenshots drastically to reduce the effort of future maintenance work.

**Comment by dmajsag** [comment]
> @dmajsag Please be aware that the browser size when taking screenshots should be set to 1440 px width. The images in this PR are a bit smaller, but it is ok for now. Just for future work :-). I recommend to delete the following images as they are of not much value and the process is obvious from the text: cra-administration-settings cra-device-list cra-endpoint-add cra-endpoint-connect We aim at reducing the overall number of screenshots drastically to reduce the effort of future maintenance work.

@BeateRixen I have used default resolution hmm will try to se it exact next time ;)
image
All files requested are removed

**Comment by BeateRixen** [comment]
@dmajsag The image links need to be removed from the corresponding md files as well, otherwise there will be an error as the image is not available.

**Comment by dmajsag** [comment]
> 

@BeateRixen OK now I know how it is done, all links removed

**Review by BeateRixen — APPROVED** [review]

**Review by BeateRixen — APPROVED** [review]

**Comment by BeateRixen** [comment]
@dmajsag Please get one approval from someone in your team.

**Review by miryalarahul — APPROVED** [review]

**Comment by BeateRixen** [comment]
@dmajsag Should I merge and graft the PRs?

**Pull request merged**
