### PR TITLE
PAQ 24.41.4 release note for security vulnerability (PAB-4378)

### PR DESCRIPTION
**Pull request by kailol-sag**
Copied over change log entry from develop and adapted the PAQ build number, ticket number, and Microservice SDK version.

### CODE REVIEW

**Comment by skom-sag** [comment]
should we call this a Fix instead of an Improvement on the 2024 line ?

**Comment by kailol-sag** [comment]
> should we call this a Fix instead of an Improvement on the 2024 line ?

Ok, I can change his.
But I would also like to hear what Beate thinks. 

We had this other PR for the CD line which was just merged into develop, and which has the "Improvement" label so that it will show up in the change log (keep in mind that fixes are not to be shown in the change log). Would you later (in a about year when the branch for the 2025 yearly release is created) also want to change this to "Fix" on the 2025 branch? This would require manual work - and that we do not forget about this! 

Or is there another way to do this? (A "Security" label as indicated on the iTrac does not sound like a bad idea to me.)

**Comment by BeateRixen** [comment]
> > > should we call this a Fix instead of an Improvement on the 2024 line ?
> > 
> > 
> > Ok, I can change his. But I would also like to hear what Beate thinks.
> > We had this other PR for the CD line which was just merged into develop, and which has the "Improvement" label so that it will show up in the change log (keep in mind that fixes are not to be shown in the change log). Would you later (in a about year when the branch for the 2025 yearly release is created) also want to change this to "Fix" on the 2025 branch? This would require manual work - and that we do not forget about this!
> > Or is there another way to do this? (A "Security" label as indicated on the iTrac does not sound like a bad idea to me.)
> 
> I do not want to change Improvement to Fix once 2025 branch is created, lets not do any additional work here.
> 
> Security is an important topic and would be good if we can improve the doc tooling to include this new section, but I would leave it to @BeateRixen. Perhaps you can discuss about adding a new security label in the workstream ?

@kailol-sag See Nikos reply in the release notes data document. I would also not want to add more change types for now but see how we come along with the existing ones after we got used to them.

But I agree I would use the same change type for the yearly release and for CD.

**Review by BeateRixen — APPROVED** [review]

**Comment by kailol-sag** [comment]
> But I agree I would use the same change type for the yearly release and for CD.
Ok, I'll keep the "Improvement" for consistency.

**Pull request merged**
