### PR TITLE
MTM-51853 open ssl command to encrypt verification code

### PR DESCRIPTION
**Pull request by mmed-softwareag**

### CODE REVIEW

**Comment by mmed-softwareag** [comment]
Should be grafted to 1016, 1017, 1018

**Comment by rssag** [comment]
@mmed-softwareag 
there's a suggestion by @BeateRixen, and this PR also needs an approval by your team

**Review by kowalczykmike — APPROVED** [review]

**Comment by kowalczykmike** [comment]
> @mmed-softwareag there's a suggestion by @BeateRixen, and this PR also needs an approval by your team

approved :)

**Review by rssag — APPROVED** [review]

**Comment by rssag** [comment]
merge conflict in 10.16.0, the enumeration is not present there (it's an unordered list), and the structure is a bit different.
i'll skip 10.16.0 for now, please have a look if we should apply this PR there. here's the 10.16.0 text: https://github.com/SoftwareAG/c8y-docs/blob/release/r10.16.0/content/device-integration/mqtt-bundle/device-certificates.md (scroll down to "Perform a proof of possession")

@mmed-softwareag

**Comment by mmed-softwareag** [comment]
Please don't backport it to 1016 - i've added consistent changes in: https://github.com/SoftwareAG/c8y-docs/pull/1147

**Pull request merged**
