### PR TITLE
PAQ: Update doc for Analytics Builder and EPL Apps consistency (PAB-4521)

### PR DESCRIPTION
**Pull request by kailol-sag**

### CODE REVIEW

**Review by nabu-nnat — APPROVED** [review]

**Comment by kailol-sag** [comment]
HI @skom-sag , we need a second approval so that you can later merge it and for me to close the iTrac. So can you please approve?

**Review by skom-sag — APPROVED** [review]

**Review by BeateRixen — APPROVED** [review]

**Review by skom-sag — APPROVED** [review]

**Comment by skom-sag** [comment]
@kailol-sag  can you help resolve the conflict ?

**Comment by kailol-sag** [comment]
> @kailol-sag can you help resolve the conflict ? perhaps just deleting the screenshot would be sufficient ?

We need to use the screenshot from this PR because I have changed it to show the new edit icon next to the model name.
And I made sure that it also has the updated book icon that is used to show/hide the documentation pane (from the other PR).

**Comment by skom-sag** [comment]
v25.167.0 is deployed to eu-latest on 11 June 2024

**Review by skom-sag — APPROVED** [review]

**Pull request merged**
