### PR TITLE
PAB-4345: Change export command to download

### PR DESCRIPTION
**Pull request by kailol-sag**
This is something which has been forgotten to update in the doc. It pertains to CD and the 2024 yearly release and can be merged immediately. And there's also a change log / release note entry for this.

@BeateRixen , when this has been approved, can you please merge this into develop and also into the y2024 branch?

### CODE REVIEW

**Review by BeateRixen — APPROVED** [review]

**Comment by BeateRixen** [comment]
@dianaolives Can you please add the change log entry to the future branch?

**Comment by BeateRixen** [comment]
@kailol-sag Any specific reason why you don´t want to merge and graft as you usually do in c8y-docs?

**Comment by kailol-sag** [comment]
> @kailol-sag Any specific reason why you don´t want to merge and graft as you usually do in c8y-docs?

Hm, I'm not sure how to handle the change log entry for the yearly release.
And for the other changes in the "normal" doc: we had autobackports for the versions up to 10.18. Guess, we'll no longer have them for the versions after 10.18? Still not sure how to do it right .... sorry.

**Comment by BeateRixen** [comment]
> > @kailol-sag Any specific reason why you don´t want to merge and graft as you usually do in c8y-docs?
> 
> Hm, I'm not sure how to handle the change log entry for the yearly release. And for the other changes in the "normal" doc: we had autobackports for the versions up to 10.18. Guess, we'll no longer have them for the versions after 10.18? Still not sure how to do it right .... sorry.

Yes, I completely understand that. Change logs/release notes are still messy and work in progress. However, everything that goes into CD should also go into the yearly releases. It is the other way round, the yearly releases additionally hold fixes. We will soon replace everything with the new format, that might make it clearer :-).

In the future, the teams are supposed to merge PRs as they know best which changes must/can go live in accordance with the software in CD. Since the changes in this PR can already go live, this is not an issue. 

I have added the backport label for 2024.

**Review by skom-sag — APPROVED** [review]

**Pull request merged**
