### PR TITLE
[DM-1755] Add German screenshots for DM-164 for German User guide

### PR DESCRIPTION
**Pull request by bggov**
This is related to [this](https://cumulocity.atlassian.net/browse/DM-1755) story task, which is about the same screenshots but on English. 
Also related to this PR: https://github.com/SoftwareAG/c8y-docs/pull/509/files

### CODE REVIEW

**Comment by rssag** [comment]
DeviceManagement/devmgmt-bulk-registration.png says:
"Register general devices in bulk", which is not German

devmgmt-register-devices-custom.png changed significantly - intended?

**Comment by bggov** [comment]
> DeviceManagement/devmgmt-bulk-registration.png says: "Register general devices in bulk", which is not German
> 
> devmgmt-register-devices-custom.png changed significantly - intended?



> DeviceManagement/devmgmt-bulk-registration.png says: "Register general devices in bulk", which is not German
> 
> devmgmt-register-devices-custom.png changed significantly - intended?

Thank you @rssag for catching this. The screenshot was updated, and a UI ticket was created for 10.15 and 10.16.

**Comment by Oezge-Akin** [comment]
@bggov For the static/images/benutzerhandbuch/DeviceManagement/devmgmt-device-registration-tenant.png one, can you take the screenshot from the management tenant. "Add to tenant" related column is not there in the new screenshot.

I think "new device hinzufügen" also not correct but it's the same situation for latest develop seems like.

**Review by Oezge-Akin — APPROVED** [review]

**Comment by pawel-rynarzewski-sag** [comment]
@Oezge-Akin "new device hinzufügen" issue will be fixed here: https://github.softwareag.com/IOTA/cumulocity-ui/pull/1998/files#r88328.

**Comment by Oezge-Akin** [comment]
> @Oezge-Akin "new device hinzufügen" issue will be fixed here: https://github.softwareag.com/IOTA/cumulocity-ui/pull/2046.

oh great thanks @pawel-rynarzewski-sag then we will update the screenshots when you merge them

**Comment by MWindel** [comment]
> > @Oezge-Akin "new device hinzufügen" issue will be fixed here: https://github.softwareag.com/IOTA/cumulocity-ui/pull/2046.
> 
> oh great thanks @pawel-rynarzewski-sag then we will update the screenshots when you merge them

@Oezge-Akin can you tag me in the PR for the new screenshots, or let me know otherwise? That would be great.

**Comment by pawel-rynarzewski-sag** [comment]
@Oezge-Akin https://github.softwareag.com/IOTA/cumulocity-ui/pull/2046 is merged

**Comment by Oezge-Akin** [comment]
> @Oezge-Akin https://github.softwareag.com/IOTA/cumulocity-ui/pull/2046 is merged

Thanks Pawel.
@MWindel now updated the screenshot here for "Add device" button change for both in English and German user guide.

**Review by rssag — APPROVED** [review]

**Pull request merged**
