### PR TITLE
Replace plus button

### PR DESCRIPTION
**Pull request by JoshuaAdemola**
Images not able to create

images/users-guide/getting-started/getting-started-knowledge-hub-button.png: **No access to knowledge hub**

images/users-guide/DeviceManagement/devmgmt-bulkoperations.png: **Only available till 10.7.0**

### CODE REVIEW

**Comment by BeateRixen** [comment]
> Images not able to create
> 
> images/users-guide/getting-started/getting-started-knowledge-hub-button.png: **No access to knowledge hub**
> 
> images/users-guide/DeviceManagement/devmgmt-bulkoperations.png: **Only available till 10.7.0**

For the first image, couldn´t you just remove the button from the screenshot? That is actually the way, I wold have done it.

**Comment by BeateRixen** [comment]
@JoshuaAdemola The image "cockpit-widget-asset-note" does not show the same content, i.e. highlighting an asset note, which is important for the context. I would actually keep it simple and just remove the button from the screenshot and move the search button to the right. 
The same with et-data-broker-alarm, the content is not the same and some missing details might be important for the context.
Please also double-check in the German screenshots you made.

**Comment by JoshuaAdemola** [comment]
> > Images not able to create
> > images/users-guide/getting-started/getting-started-knowledge-hub-button.png: **No access to knowledge hub**
> > images/users-guide/DeviceManagement/devmgmt-bulkoperations.png: **Only available till 10.7.0**
> 
> For the first image, couldn´t you just remove the button from the screenshot? That is actually the way, I wold have done it.

>Image fixed.

**Comment by JoshuaAdemola** [comment]
@BeateRixen I did not remove the search button in the "et-data-broker-alarm" image. Should I?

**Comment by JoshuaAdemola** [comment]
> 

Fixed

**Review by BeateRixen — APPROVED** [review]

**Review by MWindel — APPROVED** [review]

**Pull request merged**
