### PR TITLE
MTM-56104 add info about details of device counting for usage statistics

### PR DESCRIPTION
**Pull request by jkot-softwareag**
bakcport of https://github.com/SoftwareAG/c8y-docs/pull/2054
changed version in changelog to 10.18

### CODE REVIEW

**Review by d-mariak — APPROVED** [review]

**Comment by jkot-softwareag** [comment]
"device marker" link needs fixing

**Comment by BeateRixen** [comment]
@jkot-softwareag The release notes for 10.18 and below are in a separate repo. I will take care of adding the entry, please remove the file from here.

**Comment by jkot-softwareag** [comment]
> "device marker" link needs fixing

Done in second commit

**Comment by jkot-softwareag** [comment]
> @jkot-softwareag The release notes for 10.18 and below are in a separate repo. I will take care of adding the entry, please remove the file from here.

Done.

**Review by BeateRixen — APPROVED** [review]

**Pull request merged**
