### PR TITLE
Automated Handover: 10.18.1 Analytics Builder Block Reference Documentation.

### PR DESCRIPTION
**Pull request by apamabld**
No review required. This is just a bot handling already-reviewed material that is intended to go into the target branch without any backports.

### CODE REVIEW

**Comment by skom-sag** [comment]
> @skom-sag , do you know who kicked this off? There are no real changes on this PR, and I'm wondering if we can close this without merging.

Looks like the some of the newlines are stripped off as part of the repository refactoring.

Since this is part of an automated tooling, and the tooling hasn't changed recently, I would assume some new lines were stripped off as part of the repository refactoring.

We can go with two approaches here, 
- If the new lines aren't expected at the end of the file, we can update the tooling to not produce them 
- We can close this PR now but another PR will be opened as soon as the next streaming analytics build is promoted. We can update the tooling to strip out the new line at end of file, but it would only reflect in tomorrow's build.
- Alternatively, merge this PR with new lines now and we do not have to make any changes on the product repository.

**Comment by kailol-sag** [comment]
> We can go with three approaches here,
> 
> * If the new lines aren't expected at the end of the file, we can update the tooling to not produce them
> * We can close this PR now but another PR will be opened as soon as the next streaming analytics build is promoted. We can update the tooling to strip out the new line at end of file, but it would only reflect in tomorrow's build.
> * Alternatively, merge this PR with new lines now and we do not have to make any changes on the product repository.

The develop branch is still locked for the restructuring. My suggestion: do not yet update the tooling, close this PR for now, and wait for the next PR which will then hopefully work with the restructured repo. Do you all agree?

**Comment by skom-sag** [comment]
> > We can go with three approaches here,
> > 
> > * If the new lines aren't expected at the end of the file, we can update the tooling to not produce them
> > * We can close this PR now but another PR will be opened as soon as the next streaming analytics build is promoted. We can update the tooling to strip out the new line at end of file, but it would only reflect in tomorrow's build.
> > * Alternatively, merge this PR with new lines now and we do not have to make any changes on the product repository.
> 
> The develop branch is still locked for the restructuring. My suggestion: do not yet update the tooling, close this PR for now, and wait for the next PR which will then hopefully work with the restructured repo. Do you all agree?

We can keep this PR open till the develop branch is open. The tooling will not raise a new PR if one exists already. If there are new source changes, then an existing PR will be automatically updated.

**Comment by kailol-sag** [comment]
> We can keep this PR open till the develop branch is open. The tooling will not raise a new PR if one exists already. If there are new source changes, then an existing PR will be automatically updated.

I was just was informed that the develop branch is open again (and we just found out that I never received any announcement mails from Beate). It looks like the structure has not changed at all for the "streaming-analytics" folder. So I could just go ahead and merge this if no-one objects.

**Pull request merged**
