### PR TITLE
[MTM-57672] Removed sensor library concept from domain model documentation

### PR DESCRIPTION
**Pull request by Airdroplet**
- removed sensor library concept from product documentation

### CODE REVIEW

**Comment by Airdroplet** [comment]
I probably missed something somewhere, because menu behavior is strange. Please check preview here: https://softwareag-c8y-docs-build-pr-2036.surge.sh/concepts/domain-model/#measurements before approving. Maybe there will be an idea what kind of change is missing.

**Review by BeateRixen — APPROVED** [review]

**Comment by pawel-rynarzewski-sag** [comment]
@Airdroplet, can you specify what concerns you in the menu behavior? I don't see anything wrong on the first glance.

**Review by pawel-rynarzewski-sag — APPROVED** [review]

**Comment by Airdroplet** [comment]
> @Airdroplet, can you specify what concerns you in the menu behavior? I don't see anything wrong on the first glance.

sure, here is recording what I'm observing. Basically menu highlights wrong item.

Uploading Screencast 2024-05-13 13:23:09.mp4…

**Comment by BeateRixen** [comment]
> > @Airdroplet, can you specify what concerns you in the menu behavior? I don't see anything wrong on the first glance.
> 
> sure, here is recording what I'm observing. Basically menu highlights wrong item.
> 
> [Uploading Screencast 2024-05-13 13:23:09.mp4…](https://drive.google.com/file/d/1gAkm_Zg4PecUGPcTv5Zl_Pr0pDtsfJQd/view?usp=sharing)

This is a general issue and has always been like this, you probably did not realize so far :-). Carlos and me decided to ignore as minor.

**Pull request merged**
