### PR TITLE
Cumulocity Edge Copyright label - Develop

### PR DESCRIPTION
**Pull request by raghuvamsi-d**

### CODE REVIEW

**Comment by BeateRixen** [comment]
@raghuvamsi-d It seems this was a misunderstanding. We do not need the copyright text in all Edge md files. We only need any current copyright text referring to Software AG to be replaced in the static files located in static/files. So as far as I can see this only affects 3 files.

**Comment by raghuvamsi-d** [comment]
Sure @BeateRixen , I will amend it accordingly.

**Review by BeateRixen — APPROVED** [review]

**Comment by BeateRixen** [comment]
@raghuvamsi-d I cherry-picked the changes manually to release y2024

**Comment by raghuvamsi-d** [comment]
Many thanks ! @BeateRixen

**Pull request merged**
