### PR TITLE
[MTM-50749] Updated screenshots for Web SDK: Tutorials

### PR DESCRIPTION
**Pull request by pawel-rynarzewski-sag**

### CODE REVIEW

**Comment by pawel-rynarzewski-sag** [comment]
@BeateRixen, is it fine to have a wider screenshot in case of https://github.com/SoftwareAG/c8y-docs/pull/863/files#diff-dc042ff4e68abbfd613afcc3b4a7d1b342d00703e309c6e3133515d07c608664, where not only the application is shown, but also browser's address bar and developer tools?

**Comment by Airdroplet** [comment]
@pawel-rynarzewski-sag please replace [static/images/web-sdk/custom-client-service.png](https://github.com/SoftwareAG/c8y-docs/pull/863/files#diff-dc042ff4e68abbfd613afcc3b4a7d1b342d00703e309c6e3133515d07c608664)

Max width should be 1440 as per: 
1. Document: https://sagportal.sharepoint.com/:w:/r/sites/CumulocityIoTDocs/Shared%20Documents/General/Processes%20%26%20HowTos/Standards%20for%20taking%20screenshots%20for%20Cumulocity%20IoT%20documentation.docx?d=w3b9425bc97e14db0b7f8ff649f6d7ec2&csf=1&web=1&e=YOEoeZ
2. Presentation: https://sagportal.sharepoint.com/:p:/r/sites/CumulocityIoTDocs/Shared%20Documents/General/Processes%20%26%20HowTos/C8Y-Screenshot-Standards.pptx?d=w10f8af6795564f94b854fa69009c3c8b&csf=1&web=1&e=4odIuE

**Review by Airdroplet — APPROVED** [review]

**Comment by pawel-rynarzewski-sag** [comment]
@Airdroplet, screenshot replaced

**Comment by darluk** [comment]
should be the text displayed as the mirror image https://github.com/SoftwareAG/c8y-docs/pull/863/files#diff-bb170dcb4d4dd2d8af2470e340b0b70fb7a8f9790ae25805aa93c7d9e290e2b3

for the https://github.com/SoftwareAG/c8y-docs/pull/863/files#diff-c7c038f363d3f61517a32f0303a4b369d34bb85668224b1691b37bac362af0e7  maybe the width can be minimized not to show an empty window

**Comment by pawel-rynarzewski-sag** [comment]
@darluk, "should be the text displayed as the mirror image" - yes, that's how this particular example widget is supposed to work; "maybe the width can be minimized" - screenshot cropped.

**Review by darluk — APPROVED** [review]

**Review by darluk — APPROVED** [review]

**Comment by pawel-rynarzewski-sag** [comment]
Resolved conflicts with @pyrocreators's pull request https://github.com/SoftwareAG/c8y-docs/pull/804/files. Took mine screenshots as they were of the required resolution.

**Comment by pawel-rynarzewski-sag** [comment]
@rssag, could you please review it and add the required labels to have it on 10.17 too?

**Review by rssag — APPROVED** [review]

**Comment by rssag** [comment]
resolved the merge conflict manually: https://github.com/SoftwareAG/c8y-docs/commit/c9a689635fe0858c5c321bb0bb2fcc80f4a9bb5d

**Pull request merged**
