### PR TITLE
DM-1439 Change Actility Operations Screenshot

### PR DESCRIPTION
**Pull request by ashhSAG93**

### CODE REVIEW

**Review by miryalarahul — APPROVED** [review]

**Review by rssag — APPROVED** [review]

**Comment by rssag** [comment]
which releases does this apply to?

**Comment by rssag** [comment]
is this supposed to go to 10.14.0 also?

**Comment by ashhSAG93** [comment]
> is this supposed to go to 10.14.0 also?

Yes it has to go to 10.14 and 10.15

**Comment by rssag** [comment]
cherry-picked to 10.14.0 and 10.15.0.

**Pull request merged**
