### PR TITLE
MTM48113 spelling of protocols review

### PR DESCRIPTION
**Pull request by dianaolives**

### CODE REVIEW

**Review by sharath-jk — COMMENTED** [review]
@dianaolives, I have a request - please do not merge the changes under the "edge" folder. I have a branch that is still open and merging these changes will create merge conflicts. If possible, revert the changes for the "edge" files. I will make the same changes in the branch that I'm currently working on.

**Comment by MWindel** [comment]
@sharath-jk Please add me to the PR you create with the changes incorporated from this PR.

**Comment by BeateRixen** [comment]
@dianaolives It seems that one "edge" file still shows changes (with changes spaces, probably related to the OS). Perhaps you should copy the respective file from develop to avoid conflicts.

**Comment by dianaolives** [comment]
> @dianaolives It seems that one "edge" file still shows changes (with changes spaces, probably related to the OS). Perhaps you should copy the respective file from develop to avoid conflicts.

Ok, it was done.

**Review by BeateRixen — APPROVED** [review]

**Review by rssag — APPROVED** [review]

**Pull request merged**
