### PR TITLE
DM-1413: updated some screenshots on device protocols page

### PR DESCRIPTION
**Pull request by sourajitsaha17**

### CODE REVIEW

**Comment by BeateRixen** [comment]
@pawel-rynarzewski-sag The images devmgmt-device-protocol-add link to a wrong guide. It must be the "Protocol integration guide" (instead of the Device integration tutorials) and the link must point to https://cumulocity.com/guides/protocol-integration/overview/. @MWindel In the German translation, the grammar is wrong "in den Device integration tutorial" (used to be in den Device guides which was correct). If we change the guide and the link to the Protocol integration guide this has to be adapted as well to "im Protocol integration guide".

**Comment by BeateRixen** [comment]
@sourajitsaha17 Screenshots are correct but UI is wrong, see above :-).

**Comment by sourajitsaha17** [comment]
Hi @BeateRixen 

@dominikschmitz created a PR for the UI fix. I'll update the screenshots from there but merge it once the UI task is merged to 10.15

**Review by dominikschmitz — APPROVED** [review]

**Comment by dominikschmitz** [comment]
> Hi @BeateRixen
> 
> @dominikschmitz created a PR for the UI fix. I'll update the screenshots from there but merge it once the UI task is merged to 10.15

UI fix merged, screenshots already updated

**Review by BeateRixen — APPROVED** [review]

**Comment by MWindel** [comment]
@BeateRixen, I have made a note and will fix the string in the upcoming translation round.

**Review by Oezge-Akin — APPROVED** [review]

**Pull request merged**
