### PR TITLE
Automated Handover: 25.192.0 Analytics Builder Block Reference Documentation.

### PR DESCRIPTION
**Pull request by apamabld**
No review required. This is just a bot handling already-reviewed material that is intended to go into the target branch without any backports.

### CODE REVIEW

**Comment by kailol-sag** [comment]
This is almost the same as #2249 but it includes a doc improvement.
@skom-c8y , if you want to close one of the PRs, then you should close #2249 and not this one.

**Review by kailol-sag — APPROVED** [review]

**Comment by skom-c8y** [comment]
Closed #2249, this PR also has the fix to prevent future duplicates

**Comment by kailol-sag** [comment]
@skom-c8y , will we have a problem with merging this one? It contains the changes from 2 different builds: 25.192.0 (Counter block) and 25.199.0 (Expression block). So either one change gets published too early or the other one too late ... ???

**Comment by skom-c8y** [comment]
Let's wait for the second change to become available on eu-latest

**Pull request merged**
