### PR TITLE
modified copyright text for yearly release

### PR DESCRIPTION
**Pull request by BeateRixen**

### CODE REVIEW

**Comment by BeateRixen** [comment]
@ben-sag I added your othe rchanges without PR. This one is just to verify that the additional phrase is added correctly.

**Review by MWindel — APPROVED** [review]

**Comment by ben-sag** [comment]
> @ben-sag I added your othe rchanges without PR. This one is just to verify that the additional phrase is added correctly.

Hi @BeateRixen  actually I realised we need slightly different instructions for the non-cloud release (e.g. for a helm chart the third party info would be in a link in the README or LICENSE file), so I've updated the PR accordingly - trying to cover ourselves legally without going into too much detail that might end up being inaccurate if some teams do it a bit differently. I also think it's still helpful/safest to also mention the cloud TPs info here, but with lower prominence than the information about the annual release. Hope that looks ok, thanks for re-reviewing!!

**Comment by BeateRixen** [comment]
> > @ben-sag I added your othe rchanges without PR. This one is just to verify that the additional phrase is added correctly.
> 
> Hi @BeateRixen actually I realised we need slightly different instructions for the non-cloud release (e.g. for a helm chart the third party info would be in a link in the README or LICENSE file), so I've updated the PR accordingly - trying to cover ourselves legally without going into too much detail that might end up being inaccurate if some teams do it a bit differently. I also think it's still helpful/safest to also mention the cloud TPs info here, but with lower prominence than the information about the annual release. Hope that looks ok, thanks for re-reviewing!!

@ben-sag Yes, looks good to me.

**Comment by BeateRixen** [comment]
> > > @ben-sag I added your othe rchanges without PR. This one is just to verify that the additional phrase is added correctly.
> > 
> > 
> > Hi @BeateRixen actually I realised we need slightly different instructions for the non-cloud release (e.g. for a helm chart the third party info would be in a link in the README or LICENSE file), so I've updated the PR accordingly - trying to cover ourselves legally without going into too much detail that might end up being inaccurate if some teams do it a bit differently. I also think it's still helpful/safest to also mention the cloud TPs info here, but with lower prominence than the information about the annual release. Hope that looks ok, thanks for re-reviewing!!
> 
> @ben-sag Yes, looks good to me.
Please approve :-).

**Review by ben-sag — APPROVED** [review]

**Pull request merged**
