### PR TITLE
PAB-4371: Change log entry for security vulnerability

### PR DESCRIPTION
**Pull request by kailol-sag**
This is my first go at adding a change log entry. Not sure if I did it right. Note that I did this manually (still need to find out how to install Netlify).

https://itrac.eur.ad.sag/browse/PAB-4377 tells me to use "Security" as a tag. But this type cannot (yet?) be selected from the Hugo-generated doc. And note that I used the "change-VSkj2iV9m" value which is normally used for the Fix type - this needs to be changed to something else.

Looking forward to the feedback/corrections from the C8Y doc team.

The corresponding software build 25.34.0 is to be deployed to eu-latest tomorrow, on Feb 7th.

### CODE REVIEW

**Comment by BeateRixen** [comment]
@kailol-sag Please find all parameters and values here: https://sagportal-my.sharepoint.com/:w:/r/personal/beri_softwareag_com/Documents/[release-notes-data.docx](https://sagportal-my.sharepoint.com/:w:/r/personal/beri_softwareag_com/Documents/release-notes-data.docx?d=w5da3567f4a3148068086710d0098a295&csf=1&web=1&e=oxc8kF)?d=w5da3567f4a3148068086710d0098a295&csf=1&web=1&e=oxc8kF

**Comment by kailol-sag** [comment]
@skom-sag , Beate reminded me that fixes are normally not included in the CD change log. And it's not possible to filter for "Security", so I changed it to "Improvement" (similar to how it's been done for https://cumulocity.com/docs/change-logs/#cumulocity-10-18-45-0-update-of-3-party-protobuf-java ). It's up to the team to decide whether such as fix is to be included in the CD change log or not.

We need a decision from you now: do we still want to list this fix as an improvement in the CD change log, or should we leave the change log unchanged and close this PR and the corresponding iTrac?

**Comment by skom-sag** [comment]
Lets categorize it as an improvement

**Comment by kailol-sag** [comment]
Thanks @skom-sag . Can this go live now? I suggest that you merge this PR as soon as the software has been deployed (after we have received one more approval for this PR).

**Comment by skom-sag** [comment]
Yes, it can go live now. the build went live on eu-latest yesterday

**Pull request merged**
