### PR TITLE
DM-935: document advanced software SmartREST templates

### PR DESCRIPTION
**Pull request by georgi-huklev**

### CODE REVIEW

**Review by rssag — APPROVED** [review]
language review as commit + approval

**Comment by rssag** [comment]
@georgi-huklev which releases does this apply to?

**Comment by georgi-huklev** [comment]
> @georgi-huklev which releases does this apply to?
It is needed for 10.14

**Review by BeateRixen — APPROVED** [review]

**Review by l2p- — APPROVED** [review]

**Comment by rssag** [comment]
cherry-picked to 10.14.0.

**Pull request merged**
