### PR TITLE
Update configuring-security.md

### PR DESCRIPTION
**Pull request by sharath-jk**

### CODE REVIEW

**Review by bbyreddy — APPROVED** [review]

**Comment by sharath-jk** [comment]
@BeateRixen @MWindel @rssag - This PR needs to be backported to:

- release/r10.17.0
- release/r10.15.0

**Comment by BeateRixen** [comment]
> @BeateRixen @MWindel @rssag - This PR needs to be backported to:
> 
> * release/r10.17.0
> * release/r10.15.0

We must also backport this to 10.16 since we keep the Edge documentation here as well. @MWindel can you please review and later on take care of backporting?

**Comment by BeateRixen** [comment]
> > @BeateRixen @MWindel @rssag - This PR needs to be backported to:
> > 
> > * release/r10.17.0
> > * release/r10.15.0
> 
> We must also backport this to 10.16 since we keep the Edge documentation here as well. @MWindel can you please review and later on take care of backporting?

Just realized, that after reviewing and approving, we first need a second PR from you, @sharath-jk for the old structure (branched from 10.17).

**Comment by sharath-jk** [comment]
> > > @BeateRixen @MWindel @rssag - This PR needs to be backported to:
> > > 
> > > * release/r10.17.0
> > > * release/r10.15.0
> > 
> > 
> > We must also backport this to 10.16 since we keep the Edge documentation here as well. @MWindel can you please review and later on take care of backporting?
> 
> Just realized, that after reviewing and approving, we first need a second PR from you, @sharath-jk for the old structure (branched from 10.17).

@BeateRixen @MWindel @rssag - I've created another PR for previous release versions.

**Comment by sharath-jk** [comment]
@MWindel - is there anything I need to do here?

**Review by MWindel — APPROVED** [review]

**Pull request merged**
