### PR TITLE
MTM-53256 cockpit export screenshots 1017

### PR DESCRIPTION
**Pull request by Airdroplet**
* updated screenshots
* removed not existing screenshots from documentation text

### CODE REVIEW

**Comment by BeateRixen** [comment]
@Airdroplet We are currently working on the 10.17 German version, which runs through a translation process. To avoid conflicts I would not touch the md files here. @MWindel please make sure that the links have all been removed in the 10.17 German md files.

**Comment by Airdroplet** [comment]
> @Airdroplet We are currently working on the 10.17 German version, which runs through a translation process. To avoid conflicts I would not touch the md files here. @MWindel please make sure that the links have all been removed in the 10.17 German md files.

@dianaolives informed me about this. I have suggested to reuse some of existing screenshots. But when running the version those removed links were pointing to nothing therefor worth to check on final version of translated documentation if there is no artifacts displayed.

**Comment by Airdroplet** [comment]
@BeateRixen @dianaolives @MWindel I closing this PR without merge. Changes proposed here were for getting attention but since work is already ongoing in parallel, there is no reason to keep this one open anymore.

**Comment by BeateRixen** [comment]
> @BeateRixen @dianaolives @MWindel I closing this PR without merge. Changes proposed here were for getting attention but since work is already ongoing in parallel, there is no reason to keep this one open anymore.

@Airdroplet I will take care of your changes in a new PR and add you as reviewer after we have merged our changes.

**Pull request closed without merging**
