### PR TITLE
Dm 1903 update user guide lpwan agents

### PR DESCRIPTION
**Pull request by atulpandasag**

### CODE REVIEW

**Review by ashhSAG93 — APPROVED** [review]

**Comment by rssag** [comment]
hello,
at first glance i noticed that no screenshots have been removed (despite our recommendation). is there a reason for that?
for example:
* static/images/device-protocols/lora-actility/ora-registration-no-credentials.png
* static/images/device-protocols/lora-actility/lora-registration-no-devicetype.png
these two screenshots display error messages. they could not only be part of the text instead, but this way would have the added benefit of being searchable (if the user is searching the documentation for the error message text).

in addition, github seems to have a problem with displaying the delta for a large number of screenshots. we are currently investigating this, but the solution might be to split up the PR into smaller chunks, for example, one per section. i'll report back once the investigation is done.

**Comment by rssag** [comment]
the following screenshots seem to have a scaling issue:
* lora-thingpark-api-monitor-alarm.png

all screenshots containing a yellow/orange color frame must be revisited. there are at least two colors not matching the one from the original screenshots, which should not be the case.

**Comment by atulpandasag** [comment]
> the following screenshots seem to have a scaling issue:
> 
> * lora-thingpark-api-monitor-alarm.png
> 
> all screenshots containing a yellow/orange color frame must be revisited. there are at least two colors not matching the one from the original screenshots, which should not be the case.

I'm not sure what you mean by "scaling issue"? Can you please elaborate on it?
And Regarding the orange frame, that is the closet frame color that I could find. I updated one screenshot which had a yellow frame.

**Comment by rssag** [comment]
> > the following screenshots seem to have a scaling issue:
> > 
> > * lora-thingpark-api-monitor-alarm.png
> > 
> > all screenshots containing a yellow/orange color frame must be revisited. there are at least two colors not matching the one from the original screenshots, which should not be the case.
> 
> I'm not sure what you mean by "scaling issue"? Can you please elaborate on it? And Regarding the orange frame, that is the closest frame color that I could find. I updated one screenshot which had a yellow frame.

the screenshot looks a lot bigger. this can have different reasons.
refer to @BeateRixen 's presentation on screenshots here:
https://sagportal.sharepoint.com/:p:/r/sites/CumulocityIoTDocs/_layouts/15/Doc.aspx?sourcedoc=%7B10F8AF67-9556-4F94-B854-FA69009C3C8B%7D&file=C8Y-Screenshot-Standards.pptx&action=edit&mobileredirect=true
slide 11, "resolution & size"

same document, slide 12, "highlighting" -
hex color “FF9300” or RGB “255/147/0” for frames in screenshots. there's a lot more with the yellow border as well. both colors from this PR are off.

again, the same document suggests that some screenshots might not be necessary at all (slides 3 to 8).

**Comment by atulpandasag** [comment]
> hello, at first glance i noticed that no screenshots have been removed (despite our recommendation). is there a reason for that? for example:
> 
> * static/images/device-protocols/lora-actility/ora-registration-no-credentials.png
> * static/images/device-protocols/lora-actility/lora-registration-no-devicetype.png
>   these two screenshots display error messages. they could not only be part of the text instead, but this way would have the added benefit of being searchable (if the user is searching the documentation for the error message text).
> 
> in addition, github seems to have a problem with displaying the delta for a large number of screenshots. we are currently investigating this, but the solution might be to split up the PR into smaller chunks, for example, one per section. i'll report back once the investigation is done.

We have put these screenshots as part of the troubleshooting section so that the customer/user will have clear information on the issue he/she is facing. And regarding the searchable error message, it's already part of the title of the issue, so this makes it easy and convenient for the customer to the information about the issue.

**Comment by atulpandasag** [comment]
> > > the following screenshots seem to have a scaling issue:
> > > 
> > > * lora-thingpark-api-monitor-alarm.png
> > > 
> > > all screenshots containing a yellow/orange color frame must be revisited. there are at least two colors not matching the one from the original screenshots, which should not be the case.
> > 
> > 
> > I'm not sure what you mean by "scaling issue"? Can you please elaborate on it? And Regarding the orange frame, that is the closest frame color that I could find. I updated one screenshot which had a yellow frame.
> 
> the screenshot looks a lot bigger. this can have different reasons. refer to @BeateRixen 's presentation on screenshots here: https://sagportal.sharepoint.com/:p:/r/sites/CumulocityIoTDocs/_layouts/15/Doc.aspx?sourcedoc=%7B10F8AF67-9556-4F94-B854-FA69009C3C8B%7D&file=C8Y-Screenshot-Standards.pptx&action=edit&mobileredirect=true slide 11, "resolution & size"
> 
> same document, slide 12, "highlighting" - hex color “FF9300” or RGB “255/147/0” for frames in screenshots. there's a lot more with the yellow border as well. both colors from this PR are off.
> 
> again, the same document suggests that some screenshots might not be necessary at all (slides 3 to 8).

I have updated the mentioned screenshots as per the guidelines.

**Review by rssag — APPROVED** [review]

**Pull request merged**
