### PR TITLE
Feature/mtm 46558/update data broker screenshots

### PR DESCRIPTION
**Pull request by rohitjoshi-softwareag**
Reviewed and updated data broker screenshots for both English and German versions of the user guide.

### CODE REVIEW

**Comment by BeateRixen** [comment]
@rohitjoshi-softwareag The images have not been taken with the standard browser size according to our guidelines (1440 px width). This affects the images showing the whole screen (platform) which are too large. Could you please retake them with a browser width of 1440 px?

**Comment by rohitjoshi-softwareag** [comment]
> @rohitjoshi-softwareag The images have not been taken with the standard browser size according to our guidelines (1440 px width). This affects the images showing the whole screen (platform) which are too large. Could you please retake them with a browser width of 1440 px?

Hi Beate, can we resize the existing screenshots or should we go about repeating the whole process again? May I also know where these guidelines exist? Just so that we can be more careful next time. Thanks :)

**Comment by BeateRixen** [comment]
> > @rohitjoshi-softwareag The images have not been taken with the standard browser size according to our guidelines (1440 px width). This affects the images showing the whole screen (platform) which are too large. Could you please retake them with a browser width of 1440 px?
> 
> Hi @BeateRixen, can we resize the existing screenshots or should we go about repeating the whole process again? May I also know where these guidelines exist? Just so that we can be more careful next time. Thanks :)

Unfortunately you cannot resize them but have to retake them. But his only applies to the screenshots which show the whole screen (2 English and 2 German ones). The others can be left as they are. You can find the guidelines here: https://docs.google.com/document/d/1geBLxk35ZIiS8C2Uo15H-14oneuEEKRf0eerHqdm3fw/edit#heading=h.mi96sed6hsqe

**Comment by slc-softwareag** [comment]
@rohitjoshi-softwareag `static/images/benutzerhandbuch/enterprise-tenant/et-data-broker-group-created.png` is not only about resize as the images are looking differently, is it intentionally?

**Comment by rohitjoshi-softwareag** [comment]
> @rohitjoshi-softwareag `static/images/benutzerhandbuch/enterprise-tenant/et-data-broker-group-created.png` is not only about resize as the images are looking differently, is it intentionally?

@slc-softwareag yup. It's consistent with where English one was taken.

**Comment by rohitjoshi-softwareag** [comment]
> > > @rohitjoshi-softwareag The images have not been taken with the standard browser size according to our guidelines (1440 px width). This affects the images showing the whole screen (platform) which are too large. Could you please retake them with a browser width of 1440 px?
> > 
> > 
> > Hi @BeateRixen, can we resize the existing screenshots or should we go about repeating the whole process again? May I also know where these guidelines exist? Just so that we can be more careful next time. Thanks :)
> 
> Unfortunately you cannot resize them but have to retake them. But his only applies to the screenshots which show the whole screen (2 English and 2 German ones). The others can be left as they are. You can find the guidelines here: https://docs.google.com/document/d/1geBLxk35ZIiS8C2Uo15H-14oneuEEKRf0eerHqdm3fw/edit#heading=h.mi96sed6hsqe

@BeateRixen done. Thanks.

**Review by BeateRixen — APPROVED** [review]

**Review by slc-softwareag — APPROVED** [review]

**Pull request merged**
