### PR TITLE
MTM-42028 - Review, update and approve LWM2M user documentation

### PR DESCRIPTION
**Pull request by chbakar**
update screenshots

### CODE REVIEW

**Review by BeateRixen — APPROVED** [review]

**Review by Oezge-Akin — COMMENTED** [review]
old static/images/device-protocols/lwm2m/lwm2m-nosec-csv-example.png
had csv file example, now it's replaced with a UI screenshot. That needs to be reverted.

**Review by BeateRixen — DISMISSED** [review]

**Review by Oezge-Akin — APPROVED** [review]

**Comment by BeateRixen** [comment]
@chbakar Can be merged from our side. Please let us know to which releases these changes apply.

**Comment by BeateRixen** [comment]
@chbakar Joshua pointed me to the issue that most of the screenshots in here have the wrong size, that is they were not taken with the correct browser settings. For consistency reasons we take screenshots with a size of 1440 x 900 pixels. Otherwise, the documentation looks very messy. Please also see our guidelines for taking screenshots here: https://docs.google.com/document/d/1geBLxk35ZIiS8C2Uo15H-14oneuEEKRf0eerHqdm3fw/edit#. In case of any questions on screenshots, please get back to @JoshuaAdemola, I´m sure he can help.

**Comment by charlesBak** [comment]
Thanks Beate @BeateRixen. I will change the screenshots.

**Review by sourajitsaha17 — DISMISSED** [review]

**Review by JoshuaAdemola — APPROVED** [review]

**Pull request merged**
