### PR TITLE
Also mention Apama-ctrl-smartrulesmt in doc

### PR DESCRIPTION
**Pull request by kailol-sag**
Added Apama-ctrl-smartrulesmt to all places where Apama-ctrl-smartrules is mentioned.
@skom-sag , is this what we want?

### CODE REVIEW

**Comment by BeateRixen** [comment]
@kailol-sag Do we need to mention this microservice elsewhere in the docs?

**Comment by kailol-sag** [comment]
Hi @BeateRixen , the only place where I found this in "your" doc is in users-guide/administration/#managing-microservices - both English and German. Will you and @MWindel update this on a different PR?

**Comment by BeateRixen** [comment]
> Hi @BeateRixen , the only place where I found this in "your" doc is in users-guide/administration/#managing-microservices - both English and German. Will you and @MWindel update this on a different PR?

So what exactly do we have to add?

**Comment by kailol-sag** [comment]
@BeateRixen , here's my suggestion:

Under "Microservices subscribed by default": Use the same text as for Apama-ctrl-smartrules, and then add the following after the first sentence:
"Single tenant" for Apama-ctrl-smartrules.
"Multi tenant" for Apama-ctrl-smartrulesmt.

In addition, the Streaming Analytics Ops guide says the following for Apama-ctrl-smartrulesmt:
"The multi-tenant application should be running under the Management tenant, and every child of the Management tenant can subscribe to the application."
Not sure if you also want to add this. 
@skom-sag , what do you think?

**Comment by skom-sag** [comment]
> @BeateRixen , here's my suggestion:
> 
> Add Apama-ctrl-smartrulesmt to the table under "Microservices subscribed by default". Use the same text as for Apama-ctrl-smartrules, and then add the following after the first sentence: "Single tenant" for Apama-ctrl-smartrules. "Multi tenant" for Apama-ctrl-smartrulesmt.
> 
> In addition, the Streaming Analytics Ops guide says the following for Apama-ctrl-smartrulesmt: "The multi-tenant application should be running under the Management tenant, and every child of the Management tenant can subscribe to the application." Not sure if you also want to add this. @skom-sag , what do you think?

No, We should not change anything for both these locations. These should remain as they are.

**Comment by BeateRixen** [comment]
> > @BeateRixen , here's my suggestion:
> > Add Apama-ctrl-smartrulesmt to the table under "Microservices subscribed by default". Use the same text as for Apama-ctrl-smartrules, and then add the following after the first sentence: "Single tenant" for Apama-ctrl-smartrules. "Multi tenant" for Apama-ctrl-smartrulesmt.
> > In addition, the Streaming Analytics Ops guide says the following for Apama-ctrl-smartrulesmt: "The multi-tenant application should be running under the Management tenant, and every child of the Management tenant can subscribe to the application." Not sure if you also want to add this. @skom-sag , what do you think?
> 
> No, We should not change anything for both these locations. These should remain as they are.

Ok, thank you both, then I will not do any further changes.

**Pull request merged**
