### PR TITLE
BugherdTask_#702

### PR DESCRIPTION
**Pull request by dianaolives**

### CODE REVIEW

**Comment by BeateRixen** [comment]
@Airdroplet Could someone from your team please confirm the change for the CPU unit? We received this change request through the feedback button:

For CPU usage, the unit of "CPU milliseconds" is incorrect. It should be "CPU millicores" - this is a standard metric for Kubernetes: https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#cpu-units

**Review by jkot-softwareag — APPROVED** [review]

**Review by kaczynskid-sag — APPROVED** [review]
`milliCPU` is stated in linked docs but is interchangeably used with `millicore` to the same meaning, so seems good enough to me; consider putting [that link mentioned](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#cpu-units) by @BeateRixen on the phrase? or as a footnote?

**Review by Airdroplet — APPROVED** [review]

**Comment by Airdroplet** [comment]
> @Airdroplet Could someone from your team please confirm the change for the CPU unit? We received this change request through the feedback button:
> 
> For CPU usage, the unit of "CPU milliseconds" is incorrect. It should be "CPU millicores" - this is a standard metric for Kubernetes: https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#cpu-units

**Comment by Airdroplet** [comment]
> @Airdroplet Could someone from your team please confirm the change for the CPU unit? We received this change request through the feedback button:
> 
> For CPU usage, the unit of "CPU milliseconds" is incorrect. It should be "CPU millicores" - this is a standard metric for Kubernetes: https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#cpu-units

Checked, seems ok from my perspective also

**Comment by BeateRixen** [comment]
> `milliCPU` is stated in linked k8s docs but is interchangeably used with `millicore` to the same meaning, so seems good enough to me; consider putting [that link mentioned](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#cpu-units) by @BeateRixen on the phrase? or as a footnote?

We avoid linking to external sources as these links are not under our control.

**Pull request merged**
