### PR TITLE
MTM-51852 new screenshots for POP

### PR DESCRIPTION
**Pull request by mmed-softwareag**

### CODE REVIEW

**Comment by mmed-softwareag** [comment]
Should be grafted to 1016, 1017, 1018

**Review by BeateRixen — APPROVED** [review]

**Comment by BeateRixen** [comment]
> Should be grafted to 1016, 1017, 1018

@mmed-softwareag If this should be grafted to 10.16 we need screenshots with the old design please :-).

**Comment by rssag** [comment]
i skipped the auto-back-port label to 10.16.0, as the screenshots are not applicable to that version

**Comment by mmed-softwareag** [comment]
Yes please remove backport for 1016: screenshots for this version is done in: https://github.com/SoftwareAG/c8y-docs/pull/1147

**Pull request merged**
