### PR TITLE
MTM-50740 Change screenshots for Managing and monitoring microservices and Managing business roles for 10.17

### PR DESCRIPTION
**Pull request by karolkaczmarski-sag**
https://cumulocity.com/guides/10.16.0/users-guide/administration/#managing-microservices -> Removed screenshots presented just different tabs of the microservice, not needed IMO

https://cumulocity.com/guides/10.16.0/users-guide/administration/#business-rules -> here I combined list and edit into single screenshot

### CODE REVIEW

**Comment by jkot-softwareag** [comment]
> https://cumulocity.com/guides/10.16.0/users-guide/administration/#managing-microservices -> Removed screenshots presented just different tabs of the microservice, not needed IMO

Suggestion: maybe we can preserve one screenshot from one of microservice details with tabs? The most interesting one (if there is such)

> https://cumulocity.com/guides/10.16.0/users-guide/administration/#business-rules -> here I combined list and edit into single screenshot

Very nice idea with this combining!

**Comment by BeateRixen** [comment]
> 

@karolkaczmarski-sag @jkot-softwareag I would also definitely leave the status tab screenshot as this shows (or could show) valuable information. Deleting the other ones seems ok to me. 
Be aware that we have another PR with the changes for "alarm mapping" here: https://github.com/SoftwareAG/c8y-docs/pull/829
It seems that the ownership for "managing business rules" and "managing data" (where we also had a conflict) is not clear?

**Comment by karolkaczmarski-sag** [comment]
@jkot-softwareag @BeateRixen ok, I leave "properties" and "status" screenshots

**Review by BeateRixen — APPROVED** [review]

**Review by jkot-softwareag — APPROVED** [review]

**Comment by BeateRixen** [comment]
@karolkaczmarski-sag Should I merge this now?

**Pull request merged**
