### PR TITLE
Adding missing screenshots to getting started and cockpit user guides.

### PR DESCRIPTION
**Pull request by eniosultan**

### CODE REVIEW

**Comment by BeateRixen** [comment]
@eniosultan For the widgets-application image, could you perhaps show some more neutral applications? "badapplication" is probably not the best to show here :-).

**Comment by rssag** [comment]
was it a deliberate choice to get rid of the orange frames in some screenshots? (for example, getting-started/getting-started-small-screen-elements.png)

also, the same screenshot hat a green "active" symbol, and it's replaced with a grey "inactive". depending on the text, that may no longer fit.

**Comment by BeateRixen** [comment]
> was it a deliberate choice to get rid of the orange frames in some screenshots? (for example, getting-started/getting-started-small-screen-elements.png)
> 
> also, the same screenshot hat a green "active" symbol, and it's replaced with a grey "inactive". depending on the text, that may no longer fit.

Regarding the 1st item, I´m on it :-). Regarding the 2nd, @eniosultan please check

**Comment by eniosultan** [comment]
> was it a deliberate choice to get rid of the orange frames in some screenshots? (for example, getting-started/getting-started-small-screen-elements.png)
> 
> also, the same screenshot hat a green "active" symbol, and it's replaced with a grey "inactive". depending on the text, that may no longer fit.

Regarding the active and inactive symbols, it still fits and it doesn't matter since it is not the context of the screenshot and is not mentioned anywhere within the text.

**Comment by BeateRixen** [comment]
> > was it a deliberate choice to get rid of the orange frames in some screenshots? (for example, getting-started/getting-started-small-screen-elements.png)
> > also, the same screenshot hat a green "active" symbol, and it's replaced with a grey "inactive". depending on the text, that may no longer fit.
> 
> Regarding the active and inactive symbols, it still fits and it doesn't matter since it is not the context of the screenshot and is not mentioned anywhere within the text.

But wouldn´t it be better to show an active device here? The screen elements also show your name, Enio, so you have to redo it anyway :-).

**Review by BeateRixen — APPROVED** [review]

**Review by rssag — APPROVED** [review]

**Review by MWindel — APPROVED** [review]

**Pull request merged**
