### PR TITLE
[DM-2031] Simulator screens update

### PR DESCRIPTION
**Pull request by dmajsag**
Simulator screens update

### CODE REVIEW

**Comment by dmajsag** [comment]
> please remove the link as well as the image itself.

@BeateRixen Removed images , not sure which additional link also should be removed.

**Comment by BeateRixen** [comment]
> > please remove the link as well as the image itself.
> 
> @BeateRixen Removed images , not sure which additional link also should be removed.

The link to the image in the corresponding md file in the content section

**Comment by dmajsag** [comment]
> > > please remove the link as well as the image itself.
> > 
> > 
> > @BeateRixen Removed images , not sure which additional link also should be removed.
> 
> The link to the image in the corresponding md file in the content section

@BeateRixen All done

**Comment by BeateRixen** [comment]
> > > > please remove the link as well as the image itself.
> > > 
> > > 
> > > @BeateRixen Removed images , not sure which additional link also should be removed.
> > 
> > 
> > The link to the image in the corresponding md file in the content section
> 
> @BeateRixen All done

But where is the modified md file?

**Comment by dmajsag** [comment]
> > > > > please remove the link as well as the image itself.
> > > > 
> > > > 
> > > > @BeateRixen Removed images , not sure which additional link also should be removed.
> > > 
> > > 
> > > The link to the image in the corresponding md file in the content section
> > 
> > 
> > @BeateRixen All done
> 
> But where is the modified md file?

@Sorry Beate it is in the https://github.com/SoftwareAG/c8y-docs/pull/850/files#diff-693a48f91143d1b063ce4d36084f472dbc0362cb5f4ac9711cedd8b34350edd9. I will remove it back here. Will let you know when all is fixed

**Comment by dmajsag** [comment]
> > > > > please remove the link as well as the image itself.
> > > > 
> > > > 
> > > > @BeateRixen Removed images , not sure which additional link also should be removed.
> > > 
> > > 
> > > The link to the image in the corresponding md file in the content section
> > 
> > 
> > @BeateRixen All done
> 
> But where is the modified md file?

@BeateRixen Sorry it is in the https://github.com/SoftwareAG/c8y-docs/pull/850/files#diff-693a48f91143d1b063ce4d36084f472dbc0362cb5f4ac9711cedd8b34350edd9. I will remove it back here. Will let you know when all is fixed

**Comment by BeateRixen** [comment]
@dmajsag Got it, please revert the changes in the other PR to avoid conflicts. We need the images for device simulator in German as well. Only the images, no changes to the md file required as mentioned above.

**Comment by dmajsag** [comment]
> 

@BeateRixen All fixed. Should I add those german simulator images in the same direcory as the rest or r there suppose to be in different location

**Comment by BeateRixen** [comment]
> > 
> 
> @BeateRixen All fixed. Should I add those german simulator images in the same direcory as the rest or r there suppose to be in different location

They are here: https://github.com/SoftwareAG/c8y-docs/tree/develop/static/images/benutzerhandbuch/DeviceManagement
Same file names, different path.

**Comment by dmajsag** [comment]
> > > 
> > 
> > 
> > @BeateRixen All fixed. Should I add those german simulator images in the same direcory as the rest or r there suppose to be in different location
> 
> They are here: https://github.com/SoftwareAG/c8y-docs/tree/develop/static/images/benutzerhandbuch/DeviceManagement Same file names, different path.

@BeateRixen All screens updated and 2 deleted devmgmt-simulator-add
devmgmt-simulator-sleep

**Review by BeateRixen — APPROVED** [review]

**Comment by BeateRixen** [comment]
@dmajsag Please get one approval from someone in your team.

**Review by miryalarahul — APPROVED** [review]

**Pull request merged**
