### PR TITLE
[DM-3747] Moving SNMP docs to cumulocity-examples

### PR DESCRIPTION
**Pull request by dmajsag**
Description

SNMP is deprecated but we still have SNMP docs on our website. This has lead to confusion with presales and customers who thought this was still a product feature.

move everything related to the SNMP docs ([SNMP - Cumulocity IoT documentation](https://cumulocity.com/docs/protocol-integration/snmp/) ) to the examples repo where the code is. Don’t spend time on fixing links just move the docs for archival purposes. Create a readmy that explains that this functionality is deprecated an no longer supported by the product team.

Acceptance criterion

- Docs moved as described
- readme created as described
- Information for Release Notes

All moved to https://github.com/SoftwareAG/cumulocity-examples/pull/122

### CODE REVIEW

**Comment by BeateRixen** [comment]
@dmajsag I have a couple of questions here:
- Did you check for links from inside the rest of the documentation into these files? Even if you don´t want to care for links within these files we should not cause links breaking in the remaining documentation.
- Before we remove the section, we should announce this change, together with a link to the place where it can be found in the future. Could you perhaps add the announcement to this PR?
- - How about the SNMP Mibparser installation and operations guide? Would this go into the examples repo as well? Can we remove it from the develop branch in c8y-docs-ops as well?

**Review by bozhidardedov — APPROVED** [review]

**Comment by dmajsag** [comment]
> @dmajsag I have a couple of questions here:
> 
> * Did you check for links from inside the rest of the documentation into these files? Even if you don´t want to care for links within these files we should not cause links breaking in the remaining documentation.
> * Before we remove the section, we should announce this change, together with a link to the place where it can be found in the future. Could you perhaps add the announcement to this PR?
> * * How about the SNMP Mibparser installation and operations guide? Would this go into the examples repo as well? Can we remove it from the develop branch in c8y-docs-ops as well?

@BeateRixen 

> * *  Announcement is in the separate PR https://github.com/SoftwareAG/c8y-docs/pull/2223
> * *  Regarding links -> I will double check but I think there shouldn't be any issues with the remaining documentation
> * *  As for SNMP Mibparser it is moved also 
> * *  I will double check if we should remove it also from c8y-docs-ops 
> * *  I will also check from which version it is no longer supported

**Comment by BeateRixen** [comment]
@dmajsag Can be merged together with #2223. Please create a similar PR for the c8y-docs-ops repo.

**Review by dafkk — APPROVED** [review]

**Comment by dmajsag** [comment]
> @dmajsag Can be merged together with #2223. Please create a similar PR for the c8y-docs-ops repo.

Moved it PR is here https://github.softwareag.com/IOTA/c8y-docs-ops/pull/792/files

**Pull request merged**
